### PR TITLE
Make user-interface

### PR DESCRIPTION
**Pull request by Mohamed-js**
Make user interface and actions of tic tac toe game

### CODE REVIEW

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Great job! 👏  Both of you have done well on this project.
Let's make a few changes, and we will be done.

- [x] the game should inform the player if the selected move is invalid (without computing what an invalid move is)
- [x] the game should display board after the player move (without computing which spots on the board are taken)
- [x] the game should inform the player if the selected move is a winning move (without computing the winning move)
- [x]  the game should inform the player if the selected move is a draw move (without computing draw)
- [x] Use a game loop as below to repeat all actions for the next player's move
- [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
Example :

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
You can use a terminating variable to end the loop.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED 🛑 

Hello team! 👋 
Good job implementing the changes requested! 👍 
However, we still need to make some more changes to get the project approved 💪 
Kindly, check my comments below 👇 apply the changes and resubmit your project for a new code review ⏩ 
Good luck! 😺 
## Mandatory changes
- the game should display the board
- the code throws the following error: 'undefined local variable or method `winner'', kindly fix it
- remove all commented out code from your files
- in this milestone, the logic is not requested, but the program should work

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required 🔴 

**Hi team!**
**Good job in implementing almost all the changes:clap:. However, we just need to make these few  changes to get this project approved:muscle:.**
**Mandatory requirements**
image

- Your game has not met the above requirement. Kindly refactor your game logic to meet the requirement.

Please make the above change and resubmit for another code review.

You can contact me on slack @ enaburekhan eric

Happy coding:blush:

**Review by GzimAsani — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED  :stop_sign: 
### HELLO  **TEAM**  You did a great job implementing the changes from the last review :+1:  very nice work :+1:  but unfortunately there is one more thing that I want you to do:
- [x] Each time after finishing the game both (Winning and draw) messages are showing, kindly fix this

### **Please make the required changes and submit another review request when you are ready.**

<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

**Review by ebeagusamuel — APPROVED** [review]
# Project Approved :100: 
### Hey there :wave: 
##### Congratulations, this project is now approved and you can now move to the next milestone.
##### Good luck
slack(@ebeagusamuel)

**Pull request merged**
